# Generated by Django 4.1.7 on 2023-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='project',
            name='secondname',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
