# Generated by Django 4.1.7 on 2023-11-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0004_delete_contact_delete_student_project_secondname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secondname',
            field=models.CharField(max_length=100),
        ),
    ]
