# Generated by Django 4.1.7 on 2023-11-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0005_alter_project_secondname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='firstname',
        ),
    ]
