# Generated by Django 4.1.7 on 2023-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0010_alter_project_date_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
