# Generated by Django 4.1.7 on 2023-11-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0011_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
