# Generated by Django 4.1.7 on 2023-11-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharathapp', '0012_project_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
    ]
